# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings

#disable Soundcloud 
# soundcloud failed to init : https://github.com/searx/searx/issues/884
use_default_settings:
  engines:
    remove:
      - soundcloud
    
server:
  secret_key: "f9e603d4191caab069b021fa0568391a33c8a837b470892c64461b5dd12464f4"
  limiter: false
  image_proxy: true
  port: 8080
# bind_address: "127.0.0.1"
  bind_address: "0.0.0.0"
ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json

#redis:
#  url: redis://redis:6379/0